/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/layouts/default/AppBar.vue')['default']
    BarraNavegacado: typeof import('./src/components/BarraNavegacado.vue')['default']
    BarraNavegacao: typeof import('./src/components/BarraNavegacao.vue')['default']
    Contatos: typeof import('./src/components/Contatos.vue')['default']
    Default: typeof import('./src/layouts/default/Default.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HelloWorld2: typeof import('./src/components/HelloWorld2.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    HomeVi: typeof import('./src/components/HomeVi.vue')['default']
    Inicial: typeof import('./src/components/Inicial.vue')['default']
    Palestrantes: typeof import('./src/components/Palestrantes.vue')['default']
    Patrocinadores: typeof import('./src/components/Patrocinadores.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sobre: typeof import('./src/components/Sobre.vue')['default']
    View: typeof import('./src/layouts/default/View.vue')['default']
  }
}
